# Generated by Django 4.2.1 on 2023-05-25 13:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('suite', '0002_alter_testcase_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='folder',
            name='edited_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='testcase',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testcase',
            name='edited_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
