# Generated by Django 4.2.1 on 2023-07-17 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suite', '0006_alter_teststep_action_alter_teststep_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=500)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('edited_on', models.DateTimeField(auto_now=True)),
                ('project_folders', models.ManyToManyField(blank=True, related_name='projects', to='suite.folder')),
                ('project_testcases', models.ManyToManyField(blank=True, related_name='projects', to='suite.testcase')),
                ('project_testruns', models.ManyToManyField(blank=True, related_name='projects', to='suite.testrun')),
            ],
        ),
        migrations.AddField(
            model_name='folder',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='suite.project'),
        ),
        migrations.AddField(
            model_name='testcase',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='testcases', to='suite.project'),
        ),
        migrations.AddField(
            model_name='testrun',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='testruns', to='suite.project'),
        ),
    ]
