# Generated by Django 4.2.1 on 2023-07-20 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suite', '0008_alter_folder_project_alter_testcase_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='key',
            field=models.CharField(default='ABCD', max_length=4),
            preserve_default=False,
        ),
    ]
