# Generated by Django 4.2.1 on 2023-09-18 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suite', '0009_project_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='item_number',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='item_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='testcase',
            name='item_number',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
