# Generated by Django 4.2.1 on 2023-09-18 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suite', '0010_folder_item_number_project_item_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='item_number',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='item_number',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
