# Generated by Django 4.2.1 on 2024-02-04 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suite', '0011_alter_folder_item_number_alter_testcase_item_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='teststeprun',
            name='executed',
            field=models.BooleanField(default=False),
        ),
    ]
