# Generated by Django 4.2.1 on 2024-02-20 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suite', '0012_teststeprun_executed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testrun',
            name='date',
        ),
        migrations.AlterField(
            model_name='teststeprun',
            name='testrun',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='suite.testrun'),
        ),
    ]
